# Generated by Django 5.2 on 2025-12-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('oidActividad', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('fechaFin', models.DateField()),
                ('fechaInicio', models.DateField()),
                ('nro', models.IntegerField()),
                ('presupuestoAsignado', models.FloatField()),
                ('resultadosEsperados', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActividadDocente',
            fields=[
                ('oidActividadDocente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('denominacionCursoCatedra', models.TextField()),
                ('fechaPeriodoDictado', models.DateTimeField()),
                ('rolDesenpeniado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('oidAutor', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoInvestigacion',
            fields=[
                ('oidGrupoInvestigacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('facultadReginalAsignada', models.TextField()),
                ('correo', models.TextField()),
                ('organigrama', models.TextField()),
                ('sigla', models.CharField(max_length=45)),
                ('fuenteFinanciamiento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LineaDeInvestigacion',
            fields=[
                ('oidLineaDeInvestigacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaActividades',
            fields=[
                ('oidProgramaActividades', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('anio', models.IntegerField()),
                ('objetivosEstrategicos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDePersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeRegistro',
            fields=[
                ('oidTipoDeRegistro', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajoPublicado',
            fields=[
                ('oidTipoTrabajoPublicado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadMemoria',
            fields=[
                ('oidActividadMemoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('observaciones', models.TextField(blank=True)),
                ('Actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='EquipamientoInfraestructura',
            fields=[
                ('oidEquipamientoInfraestructura', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('denominacion', models.TextField()),
                ('descripcion', models.TextField()),
                ('fechaIncoporacion', models.DateField()),
                ('montoInvertido', models.FloatField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionBiblioteca',
            fields=[
                ('oidDocumentacionBiblioteca', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('anio', models.IntegerField()),
                ('editorial', models.TextField()),
                ('titulo', models.TextField()),
                ('autor', models.TextField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadTransferencia',
            fields=[
                ('oidActividadTransferencia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('denominacion', models.TextField()),
                ('monto', models.FloatField()),
                ('nroActividadTransferencia', models.IntegerField()),
                ('tipoActivdad', models.CharField(max_length=45)),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='InformeRendicionCuentas',
            fields=[
                ('oidInformeRendicionCuentas', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('periodoReportado', models.CharField(max_length=50)),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='Erogacion',
            fields=[
                ('oidErogacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('egresos', models.FloatField()),
                ('ingresos', models.FloatField()),
                ('numero', models.IntegerField()),
                ('tipoErogacion', models.TextField()),
                ('InformeRendicionCuentas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.informerendicioncuentas')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='LineaDeInvestigacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lineadeinvestigacion'),
        ),
        migrations.CreateModel(
            name='MemoriaAnual',
            fields=[
                ('oidMemoriaAnual', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ano', models.IntegerField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('vicedirector', models.CharField(blank=True, max_length=200)),
                ('objetivosGenerales', models.TextField(blank=True)),
                ('objetivosEspecificos', models.TextField(blank=True)),
                ('actividadesRealizadas', models.TextField(blank=True)),
                ('resultadosObtenidos', models.TextField(blank=True)),
                ('GrupoInvestigacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorias', to='app.grupoinvestigacion')),
                ('actividades', models.ManyToManyField(blank=True, related_name='memorias', through='app.ActividadMemoria', to='app.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='IntegranteMemoria',
            fields=[
                ('oidIntegranteMemoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rol', models.CharField(blank=True, max_length=100)),
                ('dedicacion', models.CharField(blank=True, max_length=100)),
                ('MemoriaAnual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.memoriaanual')),
            ],
        ),
        migrations.AddField(
            model_name='actividadmemoria',
            name='MemoriaAnual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.memoriaanual'),
        ),
        migrations.CreateModel(
            name='ParteExterna',
            fields=[
                ('oidParteExterna', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=45)),
                ('tipoParte', models.TextField()),
                ('ActividadTransferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actividadtransferencia')),
            ],
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('oidPatente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=45)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('inventor', models.CharField(blank=True, max_length=200)),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='PatenteMemoria',
            fields=[
                ('oidPatenteMemoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('MemoriaAnual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.memoriaanual')),
                ('Patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patente')),
            ],
            options={
                'unique_together': {('MemoriaAnual', 'Patente')},
            },
        ),
        migrations.AddField(
            model_name='memoriaanual',
            name='patentes',
            field=models.ManyToManyField(blank=True, related_name='memorias', through='app.PatenteMemoria', to='app.patente'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('oidpersona', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('horasSemanales', models.IntegerField()),
                ('GrupoInvestigacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
                ('tipoDePersonal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipodepersonal')),
            ],
        ),
        migrations.AddField(
            model_name='memoriaanual',
            name='integrantes',
            field=models.ManyToManyField(blank=True, related_name='memorias', through='app.IntegranteMemoria', to='app.persona'),
        ),
        migrations.CreateModel(
            name='InvestigadorDocente',
            fields=[
                ('oidinvestigadorDocente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('gradoAcademico', models.TextField()),
                ('ActividadDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actividaddocente')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('oidInvestigador', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipoInvestigador', models.TextField()),
                ('categoriaUtn', models.TextField()),
                ('dedicacion', models.TextField()),
                ('programaDeInsentivos', models.TextField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
            ],
        ),
        migrations.AddField(
            model_name='integrantememoria',
            name='Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.persona'),
        ),
        migrations.CreateModel(
            name='BecarioPersonalFormacion',
            fields=[
                ('oidbecarioPersonalFormacioncol', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipoFormacion', models.TextField()),
                ('fuenteFinanciamiento', models.TextField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
            ],
        ),
        migrations.AddField(
            model_name='lineadeinvestigacion',
            name='ProgramaActividades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programaactividades'),
        ),
        migrations.AddField(
            model_name='grupoinvestigacion',
            name='ProgramaActividades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programaactividades'),
        ),
        migrations.CreateModel(
            name='ProyectoInvestigacion',
            fields=[
                ('oidProyectoInvestigacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigoProyecto', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('objectType', models.CharField(max_length=45)),
                ('fechaFinalizacion', models.DateField()),
                ('fechaInicio', models.DateField()),
                ('nombre', models.CharField(max_length=45)),
                ('tipoProyecto', models.CharField(max_length=50)),
                ('logrosObtenidos', models.CharField(max_length=50)),
                ('fuenteFinanciamiento', models.TextField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoMemoria',
            fields=[
                ('oidProyectoMemoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('MemoriaAnual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.memoriaanual')),
                ('ProyectoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proyectoinvestigacion')),
            ],
            options={
                'unique_together': {('MemoriaAnual', 'ProyectoInvestigacion')},
            },
        ),
        migrations.AddField(
            model_name='memoriaanual',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='memorias', through='app.ProyectoMemoria', to='app.proyectoinvestigacion'),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('oidRegistro', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('Patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patente')),
                ('TipoDeRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoderegistro')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoPresentado',
            fields=[
                ('oidTrabajoPresentado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ciudad', models.TextField()),
                ('fechaInicio', models.DateTimeField()),
                ('nombreReunion', models.TextField()),
                ('tituloTrabajo', models.TextField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoPublicado',
            fields=[
                ('oidTrabajoPublicado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.TextField()),
                ('ISSN', models.CharField(max_length=55)),
                ('editorial', models.CharField(max_length=255)),
                ('nombreRevista', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('estado', models.CharField(default='Realizado', max_length=55)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.autor')),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
                ('tipoTrabajoPublicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipotrabajopublicado')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionMemoria',
            fields=[
                ('oidPublicacionMemoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('MemoriaAnual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.memoriaanual')),
                ('TrabajoPublicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajopublicado')),
            ],
            options={
                'unique_together': {('MemoriaAnual', 'TrabajoPublicado')},
            },
        ),
        migrations.AddField(
            model_name='memoriaanual',
            name='publicaciones',
            field=models.ManyToManyField(blank=True, related_name='memorias', through='app.PublicacionMemoria', to='app.trabajopublicado'),
        ),
        migrations.AlterUniqueTogether(
            name='actividadmemoria',
            unique_together={('MemoriaAnual', 'Actividad')},
        ),
        migrations.AlterUniqueTogether(
            name='integrantememoria',
            unique_together={('MemoriaAnual', 'Persona')},
        ),
        migrations.CreateModel(
            name='ActividadXPersona',
            fields=[
                ('oidActividadXPersona', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actividad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
            ],
            options={
                'unique_together': {('Actividad', 'persona')},
            },
        ),
    ]
