# Generated by Django 5.2.8 on 2025-11-19 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadDocente',
            fields=[
                ('oidActividadDocente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('denominacionCursoCatedra', models.TextField()),
                ('fechaPeriodoDictado', models.DateTimeField()),
                ('rolDesenpeniado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrupoInvestigacion',
            fields=[
                ('oidGrupoInvestigacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('facultadReginalAsignada', models.TextField()),
                ('correo', models.TextField()),
                ('organigrama', models.TextField()),
                ('sigla', models.CharField(max_length=45)),
                ('fuenteFinanciamiento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LineaDeInvestigacion',
            fields=[
                ('oidLineaDeInvestigacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaActividades',
            fields=[
                ('oidProgramaActividades', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('anio', models.IntegerField()),
                ('objetivosEstrategicos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipamientoInfraestructura',
            fields=[
                ('oidEquipamientoInfraestructura', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('denominacion', models.TextField()),
                ('descripcion', models.TextField()),
                ('fechaIncoporacion', models.DateField()),
                ('montoInvertido', models.FloatField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionBiblioteca',
            fields=[
                ('oidDocumentacionBiblioteca', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('anio', models.IntegerField()),
                ('editorial', models.TextField()),
                ('titulo', models.TextField()),
                ('autor', models.TextField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadTransferencia',
            fields=[
                ('oidActividadTransferencia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('denominacion', models.TextField()),
                ('monto', models.FloatField()),
                ('nroActividadTransferencia', models.IntegerField()),
                ('tipoActivdad', models.CharField(max_length=45)),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='InformeRendicionCuentas',
            fields=[
                ('oidInformeRendicionCuentas', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('periodoReportado', models.CharField(max_length=50)),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='Erogacion',
            fields=[
                ('oidErogacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('egresos', models.FloatField()),
                ('ingresos', models.FloatField()),
                ('numero', models.IntegerField()),
                ('tipoErogacion', models.TextField()),
                ('InformeRendicionCuentas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.informerendicioncuentas')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('oidActividad', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('fechaFin', models.DateField()),
                ('fechaInicio', models.DateField()),
                ('nro', models.IntegerField()),
                ('presupuestoAsignado', models.FloatField()),
                ('resultadosEsperados', models.TextField()),
                ('LineaDeInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lineadeinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='ParteExterna',
            fields=[
                ('oidParteExterna', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=45)),
                ('tipoParte', models.TextField()),
                ('ActividadTransferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actividadtransferencia')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('oidpersona', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('horasSemanales', models.IntegerField()),
                ('tipoDePersonal', models.TextField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigadorDocente',
            fields=[
                ('oidinvestigadorDocente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('gradoAcademico', models.TextField()),
                ('ActividadDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actividaddocente')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('oidInvestigador', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipoInvestigador', models.TextField()),
                ('categoriaUtn', models.TextField()),
                ('dedicacion', models.TextField()),
                ('programaDeInsentivos', models.TextField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
            ],
        ),
        migrations.CreateModel(
            name='BecarioPersonalFormacion',
            fields=[
                ('oidbecarioPersonalFormacioncol', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipoFormacion', models.TextField()),
                ('fuenteFinanciamiento', models.TextField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
            ],
        ),
        migrations.AddField(
            model_name='lineadeinvestigacion',
            name='ProgramaActividades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programaactividades'),
        ),
        migrations.AddField(
            model_name='grupoinvestigacion',
            name='ProgramaActividades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programaactividades'),
        ),
        migrations.CreateModel(
            name='ProyectoInvestigacion',
            fields=[
                ('oidProyectoInvestigacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigoProyecto', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('objectType', models.CharField(max_length=45)),
                ('fechaFinalizacion', models.DateField()),
                ('fechaInicio', models.DateField()),
                ('nombre', models.CharField(max_length=45)),
                ('tipoProyecto', models.CharField(max_length=50)),
                ('logrosObtenidos', models.CharField(max_length=50)),
                ('fuenteFinanciamiento', models.TextField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoPresentado',
            fields=[
                ('oidTrabajoPresentado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ciudad', models.TextField()),
                ('fechaInicio', models.DateTimeField()),
                ('nombreReunion', models.TextField()),
                ('tituloTrabajo', models.TextField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoPublicado',
            fields=[
                ('oidTrabajoPublicado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('autor', models.TextField()),
                ('titulo', models.TextField()),
                ('tipoTrabajoPublicado', models.TextField()),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadXPersona',
            fields=[
                ('oidActividadXPersona', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actividad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
            ],
            options={
                'unique_together': {('Actividad', 'persona')},
            },
        ),
    ]
