# Generated by Django 5.2 on 2025-12-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patente',
            name='numero',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
