# Generated by Django 5.2.8 on 2025-11-30 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaAnual',
            fields=[
                ('oidMemoriaAnual', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('anio', models.IntegerField()),
                ('numero', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Borrador', max_length=50)),
                ('introduccion', models.TextField(blank=True)),
                ('titulo_introduccion', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
            options={
                'ordering': ['-anio', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='IntegranteMemoria',
            fields=[
                ('oidIntegrante', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('horas', models.IntegerField()),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='app.memoriaanual')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadMemoria',
            fields=[
                ('oidActividad', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='app.memoriaanual')),
            ],
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('oidPatente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=45)),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='PatenteMemoria',
            fields=[
                ('oidPatente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patentes', to='app.memoriaanual')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoMemoria',
            fields=[
                ('oidProyecto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('responsable', models.TextField()),
                ('responsable_titulo', models.CharField(blank=True, max_length=200)),
                ('presupuesto', models.CharField(max_length=100)),
                ('colaboradores', models.TextField()),
                ('colaboradores_titulo', models.CharField(blank=True, max_length=200)),
                ('objetivos', models.TextField()),
                ('objetivos_titulo', models.CharField(blank=True, max_length=200)),
                ('resultados', models.TextField()),
                ('resultados_titulo', models.CharField(blank=True, max_length=200)),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='app.memoriaanual')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionMemoria',
            fields=[
                ('oidPublicacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=200)),
                ('revista', models.CharField(max_length=200)),
                ('anio', models.IntegerField()),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='app.memoriaanual')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('oidRegistro', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('tipoRegistro', models.TextField(max_length=45)),
                ('Patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patente')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoMemoria',
            fields=[
                ('oidTrabajo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('reunion', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=300)),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='app.memoriaanual')),
            ],
        ),
    ]
