# Generated by Django 5.2.6 on 2025-11-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaAnual',
            fields=[
                ('oidMemoriaAnual', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('anio', models.IntegerField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorias', to='app.grupoinvestigacion')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorias_como_director', to='app.persona')),
                ('vicedirector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorias_como_vicedirector', to='app.persona')),
            ],
            options={
                'ordering': ['-anio'],
                'unique_together': {('anio', 'GrupoInvestigacion')},
            },
        ),
        migrations.CreateModel(
            name='IntegranteMemoria',
            fields=[
                ('oidIntegranteMemoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rol', models.CharField(max_length=100)),
                ('horasSemanales', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
                ('MemoriaAnual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='app.memoriaanual')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadMemoria',
            fields=[
                ('oidActividadMemoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('MemoriaAnual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_memoria', to='app.memoriaanual')),
            ],
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('oidPatente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=45)),
                ('GrupoInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion')),
            ],
        ),
        migrations.CreateModel(
            name='PatenteMemoria',
            fields=[
                ('oidPatenteMemoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.TextField()),
                ('numero', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('MemoriaAnual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patentes_memoria', to='app.memoriaanual')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoMemoria',
            fields=[
                ('oidProyectoMemoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('responsable', models.TextField()),
                ('responsableTitulo', models.CharField(blank=True, max_length=200)),
                ('presupuesto', models.CharField(blank=True, max_length=100)),
                ('colaboradores', models.TextField(blank=True)),
                ('colaboradoresTitulo', models.CharField(blank=True, max_length=200)),
                ('objetivos', models.TextField(blank=True)),
                ('objetivosTitulo', models.CharField(blank=True, max_length=200)),
                ('resultados', models.TextField(blank=True)),
                ('resultadosTitulo', models.CharField(blank=True, max_length=200)),
                ('MemoriaAnual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_memoria', to='app.memoriaanual')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionMemoria',
            fields=[
                ('oidPublicacionMemoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.TextField()),
                ('autor', models.TextField()),
                ('revista', models.CharField(max_length=200)),
                ('anio', models.IntegerField()),
                ('MemoriaAnual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_memoria', to='app.memoriaanual')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('oidRegistro', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('tipoRegistro', models.TextField(max_length=45)),
                ('Patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patente')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoMemoria',
            fields=[
                ('oidTrabajoMemoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('nombreReunion', models.TextField()),
                ('titulo', models.TextField()),
                ('MemoriaAnual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='app.memoriaanual')),
            ],
        ),
    ]
