# Generated by Django 5.2.8 on 2025-12-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='perioDictado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
