# Generated by Django 5.2 on 2025-12-01 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaAnual',
            fields=[
                ('oidMemoriaAnual', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='GrupoInvestigacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.grupoinvestigacion'),
        ),
    ]
