# Generated by Django 5.2.8 on 2025-11-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_memoriaanual_integrantememoria_actividadmemoria_and_more'),
        ('app', '0002_set_default_estado'),
    ]

    operations = [
    ]
