# Generated by Django 5.2.8 on 2025-12-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_persona_periodictado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='categoriaUtn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='dedicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='denominacionCursoCatedra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='gradoAcademico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='programaDeIncentivos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='rolDesempenado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
