# Generated by Django 5.2 on 2025-12-21 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_patente_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Patente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.patente'),
        ),
        migrations.AlterField(
            model_name='trabajopresentado',
            name='tituloTrabajo',
            field=models.TextField(unique=True),
        ),
    ]
