# Generated by Django 5.2 on 2025-12-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_registro_patente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajopublicado',
            name='ISSN',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajopublicado',
            name='titulo',
            field=models.TextField(unique=True),
        ),
    ]
