# Generated by Django 5.2.8 on 2025-12-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_persona_categoriautn_persona_dedicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='categoriaUtn',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='dedicacion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='denominacionCursoCatedra',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='gradoAcademico',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='perioDictado',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='programaDeIncentivos',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='rolDesempenado',
        ),
        migrations.AddField(
            model_name='persona',
            name='imagenPerfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
