# Generated by Django 5.2 on 2025-12-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_trabajopublicado_issn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoinvestigacion',
            name='correo',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='grupoinvestigacion',
            name='nombre',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='grupoinvestigacion',
            name='sigla',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
