# Generated by Django 5.2.8 on 2025-11-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_categoriautn_dedicacion_denominacioncursocatedra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='categoriaUtn',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='denominacionCursoCatedra',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='gradoAcademico',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='rolDesempenado',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipoDePersonal',
        ),
        migrations.AddField(
            model_name='persona',
            name='categoriaUtn',
            field=models.ManyToManyField(blank=True, to='app.categoriautn'),
        ),
        migrations.AddField(
            model_name='persona',
            name='denominacionCursoCatedra',
            field=models.ManyToManyField(blank=True, to='app.denominacioncursocatedra'),
        ),
        migrations.AddField(
            model_name='persona',
            name='gradoAcademico',
            field=models.ManyToManyField(blank=True, to='app.gradoacademico'),
        ),
        migrations.AddField(
            model_name='persona',
            name='rolDesempenado',
            field=models.ManyToManyField(blank=True, to='app.roldesempenado'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipoDePersonal',
            field=models.ManyToManyField(blank=True, to='app.tipodepersonal'),
        ),
    ]
