# Generated by Django 5.2.6 on 2026-01-11 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_grupoinvestigacion_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='horasSemanales',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Las horas semanales no pueden ser negativas')]),
        ),
    ]
